### PR TITLE
generators: support customising output path

### PR DESCRIPTION
**Pull request by ixje**
This PR adds support for customising the output path through either;
1. an optional `-o` flag for the `generate` command. 
2. an optional `sdk-destinations` section under the `defaults` key in `cpm.json`, specifically
```
  "defaults": {
    ...
    "sdk-language": "python",
    "sdk-destinations": {
      "onchain": {
        "csharp": "csharp_out_dir",
        "golang": "golang_out_dir",
        "java": "java_out_dir",
        "python": "python_out_dir"
      }
    }
  }
```
All paths are relative. You only have to specify the key for the language defined in `sdk-language`. In the example above the `csharp`, `java` and `golang` keys are ignored and could be omitted.

### CODE REVIEW

**Review by lock9 — COMMENTED** [review]
Do we need to use an output folder instead of a file?

**Comment by ixje** [comment]
> Do we need to use an output folder instead of a file?

Not sure I understand the question. You have 2 options
1. you do not specify `sdk-destinations`, then the sdk will automatically be put under `/cpm_out/<language>/<contractname>/`
2. you do specificy `sdk-destinations`, then the sdk will be put under `<your_path>/<contractname>/`

**Comment by ixje** [comment]
The structure will have to change a little. The question is how;  I see 2 scenario's to serve

1. Developer wants to call `ContractX` in his own contract. 
2. Developer is author of `ContractX` and wants to make it easy callable by other smart contract developers.

For scenario `1.` I think we can assume that `developer` is only creating his contract in 1 language. Therefore the setup configuration could be simplified to
```
    "sdk-language": "python",
    "sdk-destinations": {
      "onchain": "out_dir"
      }
```

For scenario `2.` it is fair to assume that `developer` wants his contract to be easily consumable by all languages. This could mean generating SDKs for all languages and distributing them on package indices. Right now that means he must edit the `sdk-language` key for each SDK he wants to generate. The solution here could be to change `sdk-language` from being a single value to being an array.

Right now I'm leaning towards only changing `sdk-language` to be an `array` and keeping the `sdk-destinations` layout as is. This means it will be slightly more verbose for scenario `1.` than necessary, but enables scenario `2.` in a more convenient manner. Any other ideas?

ps; the `onchain` key is likely to move up one level once we start adding `offchain` sdk generation. So it will start looking more like
```json
  "defaults": {
    "contract-source-network": "mainnet",
    "contract-destination": "neo-express",
    "contract-generate-sdk": true,
    "onchain-sdks": {
      "languages": ["python"],
      "destinations": {
        "python": "python_out_dir"
      }
    },
    "offchain-sdks": {
      "languages": ["python", "go", "csharp", "java"],
      "destinations": {
        "csharp": "csharp_out_dir",
        "golang": "golang_out_dir",
        "java": "java_out_dir",
        "python": "python_out_dir"
      }
    }
  }
```

**Comment by ixje** [comment]
The new structure looks as follows (note that the main branched moved to use `yaml` over `json`) which is reflected here
```yaml
defaults:
  contract-source-network: mainnet
  contract-destination: neo-express
  contract-generate-sdk: false
  # settings related to SDK generation for on chain contracts
  on-chain:
    # both languages and destinations take the same keys values: csharp, go, java or python
    languages:
    - python
    # if not destination is given for a specific language it will output to ./cpm_out/<language>/<sdk name>
    destinations:
      python: <python_sdk_output_dir>
      java: <java_sdk_output_dir>
```
We have an `on-chain` key for all generation settings related to smart contract SDKs (that can be included by other smart contracts). Its counter part `off-chain` is for the future where we will read the settings for frontend/backend SDK generation (i.e. if a website wishes to easily invoke contract methods through an SDK)

**Review by lock9 — APPROVED** [review]

**Pull request merged**
